server:
    port: 8443
spring:
    application:
        name: VkTeams2Bitrix24

eventcheckservicecfg:
    vkTeamsBotHook: https://myteam.mail.ru/bot/v1
    vkTeamsGetFileDataHook: /files/getInfo
    vkTeamsGetEventHook: /events/get
    vkTeamsSendMessageHook: /messages/sendText
    #    vkBotToken: 001.3054308264.3514123658:1011861625
    vkBotToken: 001.2981831058.1692425810:1011975643
eventprocessingservisecfg:
    bitrix24UserHook: https://blikavto.bitrix24.ru/rest/115/8sdcenmx575wer2k/
    bitrix24AddTaskHook: tasks.task.add.json
    bitrix24UploadFileHook: disk.folder.uploadfile.json
    bitrix24AddFileToTaskHook: tasks.task.files.attach.json
    bitrix24folderId: 14149
    bitrix24DefIndexGroup: 45
    bitrix24RespID: 77
    vkChatAXO: 689432012@chat.agent
    vkChatIT: 689483635@chat.agent
#Индексы ИД чатов, где 47 - это АХО, а 45 это ИТ
#Индексы ИД Ответственных лиц, где 49 - это АХО Петриков,  а 77 это ИТ Борисенко