server:
    port: 8443
spring:
    application:
        name: VkTeams2Bitrix24

eventcheckservicecfg:
    vkTeamsBotHook: https://myteam.mail.ru/bot/v1
    vkTeamsGetFileDataHook: /files/getInfo
    vkTeamsGetEventHook: /events/get
    vkTeamsSendMessageHook: /messages/sendText
    # WorkBot
    # vkBotToken: ______ # Key
    # Test Bot
    vkBotToken: ______ # Key
eventprocessingservisecfg:
    bitrix24UserHook: ______ # Bitrix24 Hook Task rights
    bitrix24AddTaskHook: tasks.task.add.json
    bitrix24UploadFileHook: disk.folder.uploadfile.json
    bitrix24AddFileToTaskHook: tasks.task.files.attach.json
    bitrix24TasksTaskUpdateHook: tasks.task.update.json
    bitrix24folderId: ______ # Bitrix24 Folder ID
    bitrix24DefIndexGroup: ______ # Bitrix24 Default Group ID
    bitrix24RespID: ______ # Bitrix24 Default Responsible ID
    vkChatAXO: ______@chat.agent # Vk Teams Group 1
    vkChatIT: ______@chat.agent # Vk Teams Group 2
    vkChatSKLAD: ______@chat.agent # Vk Teams Group 3